### ISSUE TITLE
flit_core backend missing

### ISSUE THREAD

**Issue by GuillaumeDesforges** [nix-community/poetry2nix#568]
### Describe the issue

In `entrypoints-0.4` the backend is `flit_core.buildapi` which is specified in requires in build-system.
https://github.com/takluyver/entrypoints/blob/ebdf2d8edc9921427ea07688851999796093c240/pyproject.toml#L2-L3

Trying to build `entrypoints` in a poetry2nix mkPoetryEnv fails on build with
```
ModuleNotFoundError: No module named 'flit_core'
```

### Additional context
Entering nix shell I can check that flit_core is not available (not in pip list)
It's weird because it seems to me that poetry2nix reads the backend fields
https://github.com/nix-community/poetry2nix/blob/69cc39aa3b84c57eebc202b591c5876429e569a7/lib.nix#L161

- `default.nix`/`shell.nix`/`flake.nix`
```
{
  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.poetry2nix.url = "github:nix-community/poetry2nix";

  outputs = { self, nixpkgs, flake-utils, poetry2nix, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlay = [ poetry2nix.overlay ];
        };
      in
      {
        devShell =
          pkgs.poetry2nix.mkPoetryEnv {
            projectDir = ./.;
          };
      });
}
```

- `pyproject.toml`
```
[ tool.poetry ]
name = "poetry-nix"
version = "0.1.0"
description = ""
authors = ["Guillaume Desforges <guillaume.desforges.pro@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
entrypoints = "^0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

<details>
<summary>`poetry.lock`</summary>

```
[[package]]
name = "entrypoints"
version = "0.4"
description = "Discover and load entry points from installed packages."
category = "main"
optional = false
python-versions = ">=3.6"

[metadata]
lock-version = "1.1"
python-versions = "^3.8"
content-hash = "5d84993b5abc54589527347f1f6dcea0edde667a81ae537884ae1585c42b951a"

[metadata.files]
entrypoints = [
    {file = "entrypoints-0.4-py3-none-any.whl", hash = "sha256:f174b5ff827504fd3cd97cc3f8649f3693f51538c7e4bdf3ef002c8429d42f9f"},
    {file = "entrypoints-0.4.tar.gz", hash = "sha256:b706eddaa9218a19ebcd67b56818f05bb27589b1ca9e8d797b74affad4ccacd4"},
]
```

</details>

**Comment by flokli** [comment]
I just ran into this while trying to add `structlog` to a poetry2nix-packaged environment.

**Comment by flokli** [comment]
I read some code a bit, and added some traces.

It seems in general, there's all tooling in place to parse `build-system.build-backend`, and to add these dependencies.

However, it seems `buildSystemPkgs` isn't added to `buildInputs` (due to the `++ lib.optional isDirectory buildSystemPkgs` in `mk-poetry-dep.nix`).

I don't quite understand the bigger picture yet, why this only applies to `isDirectory`, not `isDirectory || isGit || isUrl` like in other places. It also seems `source` is null for some reason.

@adisbladis, any idea?

**Comment by flokli** [comment]
I'm able to workaround this by manually bringing in a flit-core, via the `overrides` mechanism:

```nix
poetry2nix.mkPoetryApplication {
  projectDir = ./.;
  python = python310;
  overrides = poetry2nix.overrides.withDefaults (self: super: {
    # …
    # workaround https://github.com/nix-community/poetry2nix/issues/568
    structlog = super.structlog.overridePythonAttrs (old: {
      buildInputs = old.buildInputs or [ ] ++ [ python310.pkgs.flit-core ];
    });
  });
}
```

So it seems this indeed just a matter of not automatically bringing in the build system packages for dependencies.

**Comment by GuillaumeDesforges** [comment]
Yes, I'm using this workaround as well. I've also seen that the build system dependencies are hard coded for now for a subset of packages.

https://github.com/nix-community/poetry2nix/blob/master/overrides/build-systems.json

It would be nice to parse the `requires` field in pyproject when available and add as nativeBuildInput.

**Comment by adisbladis** [comment]
The root cause of this issue is upstream https://github.com/python-poetry/poetry/issues/2789.

**Comment by GuillaumeDesforges** [comment]
Since poetry does not write the build-system.requires to the lockfile, poetry2nix can't really get that information indeed.

**Comment by flokli** [comment]
Huuh. Can we link to the upstream issue somewhere in the poetry2nix docs, and provide some guidance on how we seem to be using the overrides mechanism to manually keep track of these dependencies?

**Comment by Yajo** [comment]
Maybe could we include https://github.com/DavHau/pypi-deps-db and fetch the desired build system from there? Just like mach-nix does.

**Comment by andersk** [comment]
The upstream issue python-poetry/poetry#2789 was fixed, but the fix uses ephemeral build environments, and the information needed to reconstruct them is not recorded in the lock file. Perhaps another upstream issue should be opened explaining why it should be recorded?

**Comment by yajo** [comment]
I think upstream understands *why* it's important, but not *how* to implement it, due to a technical limitation they explained in https://github.com/python-poetry/poetry/pull/5401#issuecomment-1115392505.

Just keep that in mind, but in any case I agree to open a new issue and talk with upstream to see what solution could we get to. If solved upstream, it'd have obvious benefits upstream too, so I think they'll be open to it if there's a way to do it.

**Comment by FRidh** [comment]
I suggest doing the pinning of the build systems here in `poetry2nix` repo and let it update via actions periodically. It won't consider the version constraints that way, but it gets it working for probably 99% of the cases and is still reproducible.

**Comment by charmoniumQ** [comment]
> The upstream issue https://github.com/python-poetry/poetry/issues/2789 was fixed, but the fix uses ephemeral build environments, and the information needed to reconstruct them is not recorded in the lock file. Perhaps another upstream issue should be opened explaining why it should be recorded?

See python-poetry/poetry#6154

**Comment by IvanMalison** [comment]
Looks like https://github.com/python-poetry/poetry/pull/7975 was merged which may potentially fix this?

Has anyone tried overriding poetry with a git version to see if this fixes things?

**Comment by GuillaumeDesforges** [comment]
This example with `entrypoints` is not reproduced, probably because of https://github.com/nix-community/poetry2nix/commit/33db1f30d0a4bffdba969f731dc71e67e69038b4

If anyone would like this issue to progress, we need another new reproducible example that makes sense.

**Comment by brendon-boldt** [comment]
This `pyproject.toml` fails for the same reason I believe (`urllib3` needs `hatchling` which it can't find).  I'd test out the most recent version of poetry in poetry2nix, but I couldn't figure out how to write that override.
```toml
[tool.poetry]
name = "test"
version = "0.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "3.10"
urllib3 = "2.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by dmytrokyrychuk** [comment]
@brendon-boldt I think your problem was resolved by 33db1f3, but that version of poetry2nix  is not yet in nixpkgs. I tried your pyproject.toml with the latest poetry2nix flake, and urllib3 was installed correctly. See https://github.com/dmytrokyrychuk/nix-urllib3-test

**Comment by Turakar** [comment]
I think that the PyPI cmake package is an example of this:

pyproject.toml:

<spoiler>

```
[tool.poetry]
name = "kernel-matmul"
version = "0.1.0"
description = "Accelerated multiplications with kernel matrices"
authors = ["Turakar <turakar23@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11,<3.12"
cmake = "^3.27.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

flake.nix:
```
{
  description = "Application packaged using poetry2nix";

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    poetry2nix = {
      url = "github:nix-community/poetry2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, poetry2nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        # see https://github.com/nix-community/poetry2nix/tree/master#api for more functions and examples.
        pkgs = nixpkgs.legacyPackages.${system};
        inherit (poetry2nix.lib.mkPoetry2Nix { inherit pkgs; }) mkPoetryApplication;
      in
      {
        packages = {
          myapp = mkPoetryApplication { projectDir = self; };
          default = self.packages.${system}.myapp ;
        };

        devShells.default = pkgs.mkShell {
          inputsFrom = [ self.packages.${system}.myapp ];
          packages = [ pkgs.poetry ];
        };
      });
}
```

</spoiler>

**Comment by adisbladis** [comment]
See https://github.com/python-poetry/poetry/issues/8752

**Comment by GuillaumeDesforges** [comment]
> poetry is not going to cripple its performance just to add data to the lockfile that it does not need

IMO that makes sense, and it is best to figure out a way that does not rely on poetry changing its behavior.

It seems to me that most packages use only a very limited set of package for `build-system.requires`.
Could `poetry2nix` read `pyproject.toml` and use a mapping from these names in `build-system.requires` to packages?

E.g.

```nix
{ ... }:
let
  # from nixpkgs
  pythonPackages = ...;
  pyprojectToml = ...;
  depToDrv = {
    # For example
    "poetry-core" = pythonPackages.poetry-core;
  };
  buildRequires = map (dep: ) pyprojectToml.build-system.requires;
in
  # add `buildRequires` to the Python build
```

**Comment by adisbladis** [comment]
> It seems to me that most packages use only a very limited set of packages for build-system.requires.
> Could poetry2nix read pyproject.toml and use a mapping from these names in build-system.requires to packages?

That would be IFD, so not

**Comment by andersk** [comment]
If the reason it would be slow for Poetry to add `build-system` information to `poetry.lock` is that this information isn’t available via the PyPI HTTP API, that sounds like an argument for making it available via the PyPI HTTP API.

> Maybe we should frame our request to Poetry as "please provide a `poetry --build-from-source`".

That’s already there as the [`installer.no-binary` setting](https://python-poetry.org/docs/configuration/#installerno-binary). But it comes with this note:

“As with all configurations described here, this is a user specific configuration. This means that this is not taken into consideration when a lockfile is generated or dependencies are resolved. This is applied only when selecting which distribution for dependency should be installed into a Poetry managed environment.”

**Comment by charmoniumQ** [comment]
Are there any Python package managers that make a better lockfile? Does PDM do any better?

**Comment by yajo** [comment]
How about a `poetry2nix.lock` file? We could have a simple script here that generates that. Then, add it to your project closure and move on. Of course, to be locked impurely, just like poetry does.

**Comment by GuillaumeDesforges** [comment]
A good thing about poetry2nix was the ability to plug it on any poetry repository, including those which we don't have write permissions. Requiring a file specific to poetry2nix in any Python repo would make poetr2nix much less useful.

**Comment by yajo** [comment]
I didn't say you need to put that file in the source repository... Since that lock file is only relevant for poetry2nix (and only if you build from sources, not from wheels), then it makes sense that it resides in the same repo as the instructions to build with nix. Example:

```nix
{ poetry2nix, python310, fetchgitArgs }:
poetry2nix.mkPoetryApplication rec {
  python = python310;
  pyproject = src + ./pyproject.toml;
  poetrylock = src + ./poetry.lock;
  poetry2nixlock = ./poetry2nix.lock;
  src = builtins.fetchgit fetchgitArgs;
}
```

**Comment by MatrixManAtYrService** [comment]
The workaround indicated above didn't work for me, I think some things have been renamed since then.  

I added  `typer = "^0.15.1"` to `pyproject.toml`, and saw the error:

```
error: builder for '/nix/store/rpkk037i74csp2hmdmr34bk9zzpx288r-python3.12-click-8.1.8.drv' failed with exit code 2;
       last 25 log lines:
...
       > ModuleNotFoundError: No module named 'flit_core'
```
(click is a dependency of typer).  I ended up fixing it like this:

```nix
p2nix = poetry2nix.lib.mkPoetry2Nix { inherit pkgs; };
inherit (p2nix) mkPoetryApplication mkPoetryEditablePackage;
my-app = mkPoetryApplication { 
  projectDir = ./.;
  overrides = p2nix.defaultPoetryOverrides.extend
    (final: prev: {
      click = prev.click.overridePythonAttrs (old: {
        buildInputs = (old.buildInputs or [ ]) ++ [ pkgs.python312Packages.flit-core ];
      });
    });
};

```

**Comment by charmoniumQ** [comment]
> > > How about a poetry2nix.lock file? We could have a simple script here that generates that. Then, add it to your project closure and move on. Of course, to be locked impurely, just like poetry does.
GuillaumeDesforges
> >
> > A good thing about poetry2nix was the ability to plug it on any poetry repository, including those which we don't have write permissions. Requiring a file specific to poetry2nix in the source code repos would make poetr2nix much less useful.
>
> I didn't say you need to put that file in the source repository... Since that lock file is only relevant for poetry2nix (and only if you build from sources, not from wheels), then it makes sense that it resides in the same repo as the instructions to build with nix.

In other words, the `poetry2nix.lock` would be contained in the repository of the _ultimate user_, as opposed to any of the _intermediate users_. Presumably we would have the ability to write to the ultimate user's repo. E.g., If my ML env uses Numpy which uses Setuptools, Numpy would be an intermediate user, but my ML env would be the ultimate user and would have a `poetry2nix.lock` file saying "`setuptools==1.2.3 @ sha256-deadbeef` is a `build-system.requires` to one of the packages contained in `poetry.lock`."

`poetry2nix.lock` would be written by a **non**-hermetic tool, but once generated (hopefully relatively infrequently) it (along with `poetry.lock`) enables the rest of the dependencies to be built-from-source hermetically. We could use one of the following approaches:

* **Simple but slow**
  1. Run `poetry install` with [`no-binary :all:`](https://python-poetry.org/docs/configuration/#installerno-binary) or `pip install --no-binary :all:`.
     * The downside is that installing includes building, which is much more work than strictly necessary.
  2. Iterate over the packages of the resulting venv with `pip freeze`. For each package:
     1. Figure out the URL of the sdist corresponding with that package/version.
     2. Download and add the resulting hash to `poetry2nix.lock`.
     3. We don't have to worry about the dependencies of that package/version because they will have already been solved by `poetry install` given we set `installer.no-binary :all:`.

* **Complicated but faster**
  1. Write a function that can determine the build dependencies and run-time dependencies of a given package, using [PEP 517](https://peps.python.org/pep-0517/) or falling back to default behavior for `setuptools` projects or manual overrides. As I understand, the build dependencies are easier to figure out than the run-time dependencies, because Pip has to be able to figure out who to hand off to. Detecting the run-time dependencies only has to be done for small number of popular build-time dependencies (see Step 4.2).
  2. Create a set called build-deps and seen-build-deps.
  3. For each dependency of the ultimate user, figure out its build dependency constraints (not run dependencies, as those are managed by Poetry in `poetry.lock`), adding those to build-deps.
  4. While the build-deps is not empty,
     1. Pop a package from build-deps.
     2. Figure that packages build- _and_ run-time dependency constraints; run-time dependency of a build-time dependency of X is a build-time dependency of X, similar but simpler than the [logic for Nixpkgs itself](https://nixos.org/manual/nixpkgs/stable/#ssec-stdenv-dependencies-propagated).
     3. Add the unseen deps to build-deps and seen-build-deps.
  5. Solve the constraints in the set, probably farming out to an external lib like libmamba, libsolv. What does Pip use here?

Also note that the complicated way would be a more general tool, so it may have more community support. Anyone who wants to construct a "dependency graph of Python packages" (researchers, security folks, other package managers).
